export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM'
export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM'

export const INCREMENT_ITEM_FROM_BASKET = 'INCREMENT_ITEM_FROM_BASKET'
export const DECREMENT_ITEM_FROM_BASKET = 'DECREMENT_ITEM_FROM_BASKET'