export const PRODUCT_INCREMENT = 'PRODUCT_INCREMENT '
export const PRODUCT_DECREMENT = 'PRODUCT_DECREMENT'
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE'

export const LOAD_PRODUCT_DETAILS_REQUEST = 'LOAD_PRODUCT_DETAILS_REQUEST'
export const LOAD_PRODUCT_DETAILS_SUCCESS = 'LOAD_PRODUCT_DETAILS_SUCCESS'
export const LOAD_PRODUCT_DETAILS_FAILURE = 'LOAD_PRODUCT_DETAILS_FAILURE'