# Generated by Django 3.1.7 on 2021-05-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
